---
runtime: nodejs18
env_variables:
  service: BE-APP
  MY_VAR: my value
  NODE_ENV: production
  APP_PORT: "8080"
  FE_URL: http://localhost:3000
  SECRET: KELOMPOK1PANCINGAN
  CLOUDINARY_CLOUD_NAME: dhjpdj4ru
  CLOUDINARY_API_KEY: 569671138772217
  CLOUDINARY_API_SECRET: aEuMEJ-wWMHr_isys4a4ldcVPvw

  GCP_STORAGE_BASE_URL: https://storage.googleapis.com/vps-binar.appspot.com
  GCP_STORAGE_BUCKET_NAME: vps-binar.appspot.com
  GCP_PROJECT_ID: vps-binar
  GCP_KEY_FILENAME: vps-binar-f0b821a2bb25.json
  SUPBASE_DIRECT_URL: postgres://postgres.nxrgjzfhfpxehvapcjrr:KELMPOK1PANCINGAN@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres