---
runtime: nodejs18
env_variables:
  service: BE-APP
  MY_VAR: my value
  NODE_ENV: production
  APP_PORT: "8080"
  FE_URL: http://localhost:3000
  SECRET: KELOMPOK1PANCINGAN
  CLOUDINARY_CLOUD_NAME: dhjpdj4ru
  GCP_STORAGE_BASE_URL: https://storage.googleapis.com/vps-binar.appspot.com
  SUPBASE_DIRECT_URL: postgres://postgres.nxrgjzfhfpxehvapcjrr:KELMPOK1PANCINGAN@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres